"""Initial schema

Revision ID: f30ae74360fe
Revises: 
Create Date: 2026-07-14 13:22:37.122854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30ae74360fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_camping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camping_id', sa.String(), nullable=False),
    sa.Column('capacidad_total', sa.Integer(), nullable=False),
    sa.Column('porcentaje_buffer_offline', sa.Integer(), nullable=False),
    sa.Column('precio_base_actual', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camping_id', name='uq_unica_config_por_camping')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('dni', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'SEGURIDAD', 'CLIENTE', name='roleenum'), nullable=False),
    sa.Column('is_socio', sa.Boolean(), nullable=True),
    sa.Column('estado_cuota', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_dni'), 'usuarios', ['dni'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('reservas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fecha_reserva', sa.DateTime(), nullable=False),
    sa.Column('cantidad_personas', sa.Integer(), nullable=False),
    sa.Column('estado_pago', sa.Enum('PENDIENTE', 'PAGADO', 'CANCELADO', name='estadopagoenum'), nullable=False),
    sa.Column('jwt_jti', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_fecha_reserva'), 'reservas', ['fecha_reserva'], unique=False)
    op.create_index(op.f('ix_reservas_jwt_jti'), 'reservas', ['jwt_jti'], unique=True)
    op.create_table('ingresos_fisicos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reserva_id', sa.UUID(), nullable=True),
    sa.Column('fecha_hora_ingreso', sa.DateTime(), nullable=False),
    sa.Column('tipo_ingreso', sa.Enum('WEB', 'ESPONTANEO', name='tipoingresoenum'), nullable=False),
    sa.Column('sincronizado_offline', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingresos_fisicos_fecha_hora_ingreso'), 'ingresos_fisicos', ['fecha_hora_ingreso'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingresos_fisicos_fecha_hora_ingreso'), table_name='ingresos_fisicos')
    op.drop_table('ingresos_fisicos')
    op.drop_index(op.f('ix_reservas_jwt_jti'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_fecha_reserva'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_dni'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('configuracion_camping')
    # ### end Alembic commands ###
